Upgrade to recent TypeScript version
With the older version, it'd run into an error:

  RangeError: Maximum call stack size exceeded

Next.js automatically updated the tsconfig to set
`incremental: true`. Additionally, a newer version of SCAB was
needed, because TS's additional type checking caught that its
`fetch` definition didn't match the one solid-client was expecting.